#!/bin/sh
set -e
DUAL_BOOT_DIR="/usr/share/dualboot"
. $DUAL_BOOT_DIR/fydeos_util.sh

if ! is_dualboot ;then
    exit
fi

gpt_cnf=/usr/sbin/write_gpt.sh
root_disk=$(rootdev -d)
tmp_gpt=$(create_tmp_gpt_conf $gpt_cnf $root_disk)

if ! cmp_files $tmp_gpt $gpt_cnf; then
    mount -o remount rw /
    cp $tmp_gpt $gpt_cnf
    mount -o remount ro /
fi
